package ro.unitbv.spec.lab8;

/**
 * This is a support project for SPEC Lab 8.
 * 
 * At the end of the main method a stream of weather events is
 * generated from a CSV file. Each line of the CSV file is pushed to
 * a reactive PublishSubject<String>.
 * 
 * The stream of strings should be processed in the following way:
 * 
 * 1) Split the lines by the "," character (CSV separator)
 * 2) Create a weather event using the CSV line tokens;
 * 3) Remove "\"" characters from the names of the acquisition stations;
 * 4) Keep only the events generated by the acquisition stations starting with character "C";
 * 5) Display the events.
 *  
 * 
 * Documentation: http://reactivex.io/documentation/operators.html
 * 
 * @author dan.puiu
 * 
 */

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;

import ro.unitbv.spec.lab8.events.WeatherEvent;
import rx.subjects.PublishSubject;

public class MainMapAndFilter {

	public static void main(String... str) {

		PublishSubject<String> stream = PublishSubject.create();

		stream

		//Put your code here
		
		
		.forEach(value -> {
			System.out.println(value);
		});

		try {
			BufferedReader br = new BufferedReader(new FileReader("Resources/TemperatureEventMR.csv"));

			String line = br.readLine();
			while ((line = br.readLine()) != null)
				stream.onNext(line);

			br.close();

		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		System.out.println("Finish");

	}

}
